### ISSUE TITLE
Devices using the same ID

### ISSUE THREAD

**Issue by feletoch** [ESPresense/ESPresense#18]
I have a Mi Band 5 and a Amazfit Bip S. they have the same id, they would switch when one is not in range
![image](https://user-images.githubusercontent.com/7959637/132471543-58caf95e-3e78-4745-b611-63f1ec4656c2.png)

**Comment by DTTerastar** [comment]
Are the mac's randomized?  If not we can just have it use the mac as the fingerprint for 0x0157 which is apparently Anhui Huami Information Technology Co., Ltd. (http://domoticx.com/bluetooth-company-identifiers/)

If not we can have the verbose flavor print out all the manufacture data so we can find something to add to the fingerprint (:26 just means there is 26 bytes of data).

I WISH we could use name as id, but it only comes in 3 out of 4 packets and by then we've already assigned an id.

**Comment by feletoch** [comment]
I restarted the watch and they seem to use the same mac afterward

**Comment by DTTerastar** [comment]
v1.2.0 should resolve the issue, i'm using the mac as the fingerprint for that case now.

**Comment by feletoch** [comment]
That's awkward, the issue is back
![image](https://user-images.githubusercontent.com/7959637/133033197-12e948b8-1995-489b-a649-f2d5f8316e04.png)

**Comment by DTTerastar** [comment]
Ok, I know what that is... Multiple advertisements w/ the same mac causes issues.  Same as #23

**Comment by DTTerastar** [comment]
Ok, the newest build should fix this.  It might for 1 packet report as sid:* but once the md packet is received it'll use the mifit:<mac> as the id. 

I found this interesting doc about that device: http://changy-.github.io/articles/xiao-mi-band-protocol-analyze.html
